<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmBuildNative>false</WasmBuildNative>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../ExerciseEngine/ExerciseEngine.csproj" /></ItemGroup>
  <Target Name="ExportCompilerReferences" AfterTargets="Build">
    <ItemGroup><CompilerReference Include="@(ReferencePath)" Condition="'%(ReferencePath.NuGetPackageId)' == 'Microsoft.NETCore.App.Ref'" /></ItemGroup>
    <Copy SourceFiles="@(CompilerReference)" DestinationFolder="$(OutputPath)compiler-refs" />
  </Target>
</Project>
